name: Xquare Deploy for Production
on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: prod
          access_key: ${{ secrets.ADMIN_ACCESS }}
          github_token: ${{ secrets.PICK_ACCESS_TOKEN }}
          yarn_docker_build: true
          run: yarn start