name: Xquare Deploy for Production
on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --immutable

      - name: NodeJS Installation ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate Environment Variables File for Production
        run: |
            echo "NEXT_PUBLIC_PICK_BASE_URL=$NEXT_PUBLIC_PICK_BASE_URL" >> .env
            echo "NEXT_PUBLIC_HTTP_ONLY=$NEXT_PUBLIC_HTTP_ONLY" >> .env
          env:
            NEXT_PUBLIC_PICK_BASE_URL: ${{ secrets.NEXT_PUBLIC_PICK_BASE_URL }}
            NEXT_PUBLIC_HTTP_ONLY: ${{ secrets.NEXT_PUBLIC_HTTP_ONLY }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: prod
          access_key: ${{ secrets.ADMIN_ACCESS }}
          github_token: ${{ secrets.PICK_ACCESS_TOKEN }}